# Generated by Django 4.2.7 on 2023-11-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0004_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendStack',
            fields=[
                ('fid', models.AutoField(editable=False, help_text='Friend ID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='Friend request receiver', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user_set', to='public.user')),
                ('sender', models.ForeignKey(help_text='Friend request sender', on_delete=django.db.models.deletion.CASCADE, related_name='sender_user_set', to='public.user')),
            ],
        ),
    ]
