# Generated by Django 4.2.7 on 2023-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(editable=False, help_text='User ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('city', models.CharField(max_length=50, verbose_name='City of Residence')),
                ('state', models.CharField(max_length=50, verbose_name='State / Province')),
                ('bio', models.TextField(max_length=300, verbose_name='Bio / Profile headline')),
            ],
        ),
    ]
